site_name: Python for Networking - Building Tools & Automation
site_url: https://blue-hexagon.github.io/python-for-networking/
theme:
  favicon: images/favicon.png
  icon:
    logo: material/language-python
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - content.code.copy  # Enables "Copy" button in code blocks
    - content.code.annotate
    - content.code.select
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode


    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Fira Code



nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting_started/introduction.md
      - Virtual Environments: getting_started/virual_environments.md
      - The 'Main' Issue: getting_started/the_main_issue.md
      - Scoping: getting_started/scope_rules_in_python.md
      - PEP8: getting_started/pep8_overview.md
      - Git Crashcourse: getting_started/git_crashcourse.md
  - The Basics of Python:
      - Introduction: python_beginner/introduction.md
      - Elementary Datatypes: python_beginner/elementary_datatypes.md
  - Building Proficiency with Python:
      - Introduction: python_intermediate/introduction.md
  - Mastering Python:
      - Introduction: python_advanced/introduction.md
  - Becoming a Network Pythonista:
      - Introduction: python_mastery/introduction.md

plugins:
  - search
  - mkdocstrings
  - mermaid2
  - glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - admonition
  - md_in_html
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys

extra_css:
  - overrides/styles.css